Repository doctrine/inflector, pull requests merged in 2020-05, with the labels that each got.

#139 Add support for custom rules
  docs/en/index.rst
  lib/Doctrine/Common/Inflector/Inflector.php
  lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php
  lib/Doctrine/Inflector/InflectorFactory.php
  lib/Doctrine/Inflector/LanguageInflectorFactory.php
  lib/Doctrine/Inflector/Rules/English/InflectorFactory.php
  lib/Doctrine/Inflector/Rules/French/InflectorFactory.php
  lib/Doctrine/Inflector/Rules/NorwegianBokmal/InflectorFactory.php
  lib/Doctrine/Inflector/Rules/Portuguese/InflectorFactory.php
  lib/Doctrine/Inflector/Rules/Spanish/InflectorFactory.php
  lib/Doctrine/Inflector/Rules/Turkish/InflectorFactory.php
  lib/Doctrine/Inflector/RulesetInflector.php
  tests/Doctrine/Tests/Common/Inflector/InflectorTest.php
  tests/Doctrine/Tests/Inflector/InflectorFactoryTest.php
  tests/Doctrine/Tests/Inflector/InflectorFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/French/FrenchFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/NorwegianBokmal/NorwegianBokmalFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/Portuguese/PortugueseFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/Spanish/SpanishFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/Turkish/TurkishFunctionalTest.php
  tests/Doctrine/Tests/Inflector/RulesetInflectorTest.php
Labels: Improvement

#141 Drop legacy inflector classes and prepare 2.0 release
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  lib/Doctrine/Common/Inflector/Inflector.php
  phpcs.xml.dist
  roave-backward-compatibility-check.phar
  tests/Doctrine/Tests/Common/Inflector/InflectorTest.php
Labels: Improvement

#142 Fix plural of media breaking change
  lib/Doctrine/Inflector/Rules/English/Uninflected.php
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
Labels: Bug

#143 Fixed conversion of the word "status" to singular
  lib/Doctrine/Inflector/Rules/English/Inflectible.php
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
Labels: Bug

#146 Remove executable from version control
  .github/workflows/continuous-integration.yml
  .travis.yml
  roave-backward-compatibility-check.phar
Labels: Bug, CI

#148 Merge 1.4.x into 2.0.x
  .github/workflows/continuous-integration.yml
  .travis.yml
  lib/Doctrine/Inflector/Rules/English/Inflectible.php
  lib/Doctrine/Inflector/Rules/English/Uninflected.php
  roave-backward-compatibility-check.phar
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
Labels: Bug

#152 Fixed conversion of the word "campus" to singular
  lib/Doctrine/Inflector/Rules/English/Inflectible.php
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
Labels: Bug

#159 Test against PHP 8
  .travis.yml
  composer.json
Labels: CI, Enhancement

#162 Fix handling of multiple rulesets
  lib/Doctrine/Inflector/RulesetInflector.php
  tests/Doctrine/Tests/Inflector/RulesetInflectorTest.php
Labels: Bug
