Repository doctrine/inflector, pull requests merged in 2022-09, with the labels that each got.

#202 Ensures that Tights, and Shorts and Blouse are single/pluralised properly
  lib/Doctrine/Inflector/Rules/English/Inflectible.php
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
Labels: Bug

#206 Bump GHA workflows, run tests on PHP 8.2
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#205 Bump Doctrine CS to 10.0
  composer.json
  lib/Doctrine/Inflector/Rules/English/Inflectible.php
  lib/Doctrine/Inflector/Rules/English/Uninflected.php
  lib/Doctrine/Inflector/Rules/French/Inflectible.php
  lib/Doctrine/Inflector/Rules/French/Uninflected.php
  lib/Doctrine/Inflector/Rules/NorwegianBokmal/Inflectible.php
  lib/Doctrine/Inflector/Rules/NorwegianBokmal/Uninflected.php
  lib/Doctrine/Inflector/Rules/Portuguese/Inflectible.php
  lib/Doctrine/Inflector/Rules/Portuguese/Uninflected.php
  lib/Doctrine/Inflector/Rules/Spanish/Inflectible.php
  lib/Doctrine/Inflector/Rules/Spanish/Uninflected.php
  lib/Doctrine/Inflector/Rules/Turkish/Inflectible.php
  lib/Doctrine/Inflector/Rules/Turkish/Uninflected.php
  tests/Doctrine/Tests/Inflector/InflectorFactoryTest.php
  tests/Doctrine/Tests/Inflector/InflectorFunctionalTest.php
  tests/Doctrine/Tests/Inflector/InflectorTest.php
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/French/FrenchFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/LanguageFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/NorwegianBokmal/NorwegianBokmalFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/Portuguese/PortugueseFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/Spanish/SpanishFunctionalTest.php
  tests/Doctrine/Tests/Inflector/Rules/Turkish/TurkishFunctionalTest.php
Labels: Code Style

#204 Remove duplicate tests for English inflections
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
Labels: Test Suite
