Repository doctrine/inflector, pull requests merged in 2024-05, with the labels that each got.

#248 Setup dependabot
  .github/dependabot.yml
  .github/workflows/continuous-integration.yml
Labels: CI

#251 [FIX] Wrong pluralization of "stadium"
  lib/Doctrine/Inflector/Rules/English/Inflectible.php
  tests/Doctrine/Tests/Inflector/Rules/English/EnglishFunctionalTest.php
Labels: Bug

#253 Analyze test directory
  psalm.xml
Labels: Static Analysis

#255 Maintenance
  .github/workflows/composer-lint.yml
  composer.json
  psalm.xml
  src/Rules/Patterns.php
Labels: CI
