Repository doctrine/inflector, pull requests merged in 2025-07, with the labels that each got.

#230 add 'alga' to irregular words list
  src/Rules/English/Inflectible.php
  tests/Rules/English/EnglishFunctionalTest.php
Labels: Bug

#283 Use the proper operator
  tests/CachedWordInflectorTest.php
  tests/InflectorTest.php
Labels: Static Analysis

#284 Upgrade PHPStan to level 10
  phpstan.neon.dist
Labels: Static Analysis

#294 Use PHP 8.4 in the CI
  .github/workflows/continuous-integration.yml
Labels: CI
